-- Database and table creation
CREATE DATABASE spotify_project;

USE DATABASE spotify_project;

CREATE OR REPLACE TABLE ARTIST_TABLE (
    MODE_COUNT INT,
    TRACK_COUNT INT,
    ACOUSTICNESS FLOAT,
    ARTISTS STRING,
    DANCEABILITY FLOAT,
    DURATION_MS INT,
    ENERGY FLOAT,
    INSTRUMENTALNESS FLOAT,
    LIVENESS FLOAT,
    LOUDNESS FLOAT,
    SPEECHINESS FLOAT,
    TEMPO FLOAT,
    VALENCE FLOAT,
    POPULARITY INT,
    KEY INT
);

CREATE OR REPLACE TABLE TRACKS_TABLE (
    GENRES STRING,
    ARTISTS STRING,
    ACOUSTICNESS FLOAT,
    DANCEABILITY FLOAT,
    DURATION_MS INT,
    ENERGY FLOAT,
    INSTRUMENTALNESS FLOAT,
    LIVENESS FLOAT,
    LOUDNESS FLOAT,
    SPEECHINESS FLOAT,
    TEMPO FLOAT,
    VALENCE FLOAT,
    POPULARITY FLOAT,
    KEY INT,
    MODE_COUNT INT,
    TRACK_COUNT INT
);
